# Generated by Django 5.0.4 on 2024-05-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_groceryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
